apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169442528
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169442528
    app.kubernetes.io/part-of: test-app-169442528
  name: go-169442528
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-169442528
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-169442528
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/redhat-user-workloads/skhileri-tenant/test-app-169442528/go-169442528@sha256:3011bba6a076d1c8755d2c3a07a815f6340264516173d54c1377f9b74bf3dd09
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
